### ISSUE TITLE
Reference Azure Tasks like SonarQubeAnalyze

### ISSUE THREAD

**Issue by MatthewDavidCampbell** [tomaustin700/YAMLPipelineValidator#9]
How can YAML referencing tasks like [SonarQubeAnalyze ](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/sonar-qube-analyze-v5?view=azure-pipelines) from Azure be done?  Basic tasks UseDotNet@2 are fine but other taks without a reference throw an error: "A task is missing".

Assuming the web portal uses the PIPELINE_URL environment variable pointing to a private DevOps account.  Sent the payload to our organisations REST API endpoint but it fires back Pipeline YAML unrelated to what was posted.

Haven't used the Azure REST API before until I looked at your project.  Guessing that you have a default pipeline id.  Also curious how the DevOps pipeline has been created (namely to validate only what is posted).

**Comment by tomaustin700** [comment]
Hi @MatthewDavidCampbell, you're absolutely right and `PIPELINE_URL` points to a private DevOps account which doesn't have the task installed. If you give me a list of the tasks that you're seeing issues with I can install them which will make your problem go away. It's also fairly easy to validate a pipeline using the DevOps api which will fix your missing task issue as well. 

You need to send a HTTP post message at `https://dev.azure.com/OrgName/ProjectName/_apis/pipelines/PipelineId/runs?api-version=5.1-preview` (update OrgName, ProjectName and PipelineId to match your values) and set the body of your HTTP message to be Json and the content to be:
```json
{
  "PreviewRun" : "true",
  "YamlOverride" : "fdgdfdfg"
}

```
`YamlOverride` should be the YAML you want to validate. In order to authenticate you need to generate a PAT and use Basic Auth with the PAT as a password and username blank.

Hope this helps

**Comment by MatthewDavidCampbell** [comment]
Alright. Missed the YamlOverride in the Controller with the Validate method. ;-) Will try that out. The DevOps documentation was a tad shaky and prior to finding your extension didn’t know the REST API existed.

**Comment by MatthewDavidCampbell** [comment]
Can verify that using yamlOverride checks the syntax as expected.  Thanks Tom!
